apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "darp.dapr.io/v1alpha1",
          "kind": "Dapr",
          "metadata": {
            "name": "dapr-sample"
          },
          "spec": {
            "global": {
              "daprControlPlaneOs": "linux",
              "dnsSuffix": ".cluster.local",
              "ha": {
                "disruption": {
                  "maximumUnavailable": "25%",
                  "minimumAvailable": ""
                },
                "enabled": false,
                "replicaCount": 3
              },
              "imagePullPolicy": "IfNotPresent",
              "imagePullSecrets": "",
              "issuerFilenames": {},
              "k8sLabels": {
                "app.kubernetes.io/component": "{{ .Values.component }}",
                "app.kubernetes.io/managed-by": "helm",
                "app.kubernetes.io/name": "{{ .Release.Name }}",
                "app.kubernetes.io/part-of": "dapr",
                "app.kubernetes.io/version": "{{ .Values.global.tag }}"
              },
              "labels": {},
              "logAsJson": false,
              "mtls": {
                "allowedClockSkew": "15m",
                "enabled": true,
                "workloadCertTTL": "24h"
              },
              "nodeSelector": {},
              "prometheus": {
                "enabled": true,
                "port": 9090
              },
              "rbac": {
                "namespaced": false
              },
              "registry": "docker.io/daprio",
              "tag": "1.10.7",
              "tolerations": []
            }
          }
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.13.0+git
    operators.operatorframework.io/project_layout: helm.sdk.operatorframework.io/v1
  name: dapr-operator.v0.0.3
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: Dapr
      name: daprs.darp.dapr.io
      version: v1alpha1
  description: dapr
  displayName: Dapr Helm Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - get
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
        - apiGroups:
          - darp.dapr.io
          resources:
          - daprs
          - daprs/status
          - daprs/finalizers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - clusterrolebindings
          - clusterroles
          verbs:
          - '*'
        - apiGroups:
          - admissionregistration.k8s.io
          resources:
          - mutatingwebhookconfigurations
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - secrets
          - serviceaccounts
          - services
          verbs:
          - '*'
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - rolebindings
          - roles
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: dapr-operator-controller-manager
      deployments:
      - name: dapr-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=10
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources: {}
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                - --leader-election-id=dapr-operator
                image: docker.io/lburgazzoli/dapr-operator:v0.0.3
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 200m
                    memory: 100Mi
                  requests:
                    cpu: 100m
                    memory: 60Mi
                securityContext:
                  allowPrivilegeEscalation: false
              securityContext:
                runAsNonRoot: true
              serviceAccountName: dapr-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: dapr-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - dapr
  links:
  - name: Dapr Operator
    url: https://dapr-operator.domain
  maintainers:
  - email: lburgazzoli@gmail.com
    name: lb
  maturity: alpha
  provider:
    name: Dapr
  version: 0.0.3
