# permissions for end users to edit daprs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dapr-editor-role
rules:
- apiGroups:
  - darp.dapr.io
  resources:
  - daprs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - darp.dapr.io
  resources:
  - daprs/status
  verbs:
  - get
