# permissions for end users to view daprs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dapr-viewer-role
rules:
- apiGroups:
  - darp.dapr.io
  resources:
  - daprs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - darp.dapr.io
  resources:
  - daprs/status
  verbs:
  - get
