# permissions for end users to view daprs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: dapr-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: dapr-operator
    app.kubernetes.io/part-of: dapr-operator
    app.kubernetes.io/managed-by: kustomize
  name: dapr-viewer-role
rules:
- apiGroups:
  - dapr.dapr.io
  resources:
  - daprs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dapr.dapr.io
  resources:
  - daprs/status
  verbs:
  - get
