apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: dapr-catalog
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: quay.io/lburgazzoli/dapr-operator-catalog:latest
  displayName: Dapr Catalog
  publisher: dapr.io
  updateStrategy:
    registryPoll:
      interval: 10m
