name: build

on:
  #pull_request:
  #  branches:
  #    - main
  push:
    tags:
      - "v*"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

env:
  IMAGE_VERSION: ${{ github.ref_name}}
  IMAGE_TAG_BASE: "quay.io/lburgazzoli/dapr-operator"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check-out
        uses: actions/checkout@v3
      - name: Install CLI tools from GitHub
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          source: "github"
          github_pat: ${{ github.token }}
          operator-sdk: "latest"
      - name: Login to Quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
      - name: Build Operator Container Image
        run: |
          export VERSION=${IMAGE_VERSION#$v}

          make docker-build
          #make docker-push
      - name: Build Operator Bundle
        run: |
          export VERSION=${IMAGE_VERSION#$v}

          make bundle
          make bundle-build
          #make bundle-push
      - name: Build Operator Catalog
        run: |
          export VERSION=${IMAGE_VERSION#$v}

          make catalog-build
          #make catalog-push
